name: learn-github-actions
on:
  push:
    branches:
      - master
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: npm install -g jsdoc
      - run: jsdoc -v
